Metrics/LineLength:
  Max: 150
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 100

Style/BlockComments:
  Enabled: false

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/IfUnlessModifier:
  Enabled: false
